### PR TITLE
Fix/Clarify container removal

### PR DESCRIPTION
**Pull request by carpawell**

### CODE REVIEW

**Review by cthulhu-rider — APPROVED** [review]
LGTM

**Comment by realloc** [comment]
Shouldn't we decide on container lock/hold procedure first?

**Comment by carpawell** [comment]
> Shouldn't we decide on container lock/hold procedure first?

Yes, lets discuss it first and then correct that PR according to the decision.

**Comment by realloc** [comment]
Note: In S3 API you can't remove a non-empty bucket, hence there is no such issue. In NeoFS we can't check container content on DELETE operation, so some additional container lock/hold mechanism is required.

Related: nspcc-dev/neofs-contract#247

**Comment by roman-khimov** [comment]
The PR describes the way things work now and having this documentation is better than not having it. If the way things work is to change, we'll change the documentation accordingly.

**Pull request merged**
