### PR TITLE
Maintenance node state and status code

### LINKED ISSUE #237: Maintenance mode support
- Add `MAINTENANCE_MODE` status code. It should be returned on every public API call if a Node is in maintenance mode.
- Add `MAINTENANCE` [Node state](https://github.com/nspcc-dev/neofs-api/blob/4de2570e1a3dfc9633bbf02daf74753e7ba46b69/netmap/types.proto#L226).

### PR DESCRIPTION
**Pull request by fyrchik**
Close #237 .

### CODE REVIEW

**Review by cthulhu-rider — APPROVED** [review]

**Comment by carpawell** [comment]
@realloc, I wanted to pay attention to the fact that the current PR adds the status and the mode but does not mention them in any API method like we usually [do](https://github.com/nspcc-dev/neofs-api/blob/15eaf93ba1eb6947fb6e0927a1e6c430866cfa52/container/service.proto#L71-L78).

**Comment by realloc** [comment]
@fyrchik: Agree with @carpawell. Could you please fix this?

**Comment by carpawell** [comment]
Oh, I missed that the new status was added to the `SECTION_FAILURE_COMMON`. Well, it is already included in all our APIs then. The one question left: should a node respond with `NODE_UNDER_MAINTENANCE` on *every* API call? Even on `NetmapSnapshot`, and other non-storage-engine requests?

**Comment by fyrchik** [comment]
I think maintenance can be much more broader that replacing a disk, so unless we want to fix the API later, it is easier to respond with this status to every RPC. Responding with success if we are under maintenance is not against the spec.

**Pull request merged**
